---
# vars file for ec2_create

# Master customization
master_vm_type: "t2.micro"                                  # General Purpose: 1 vCPU, 1 GB Memory
#master_vm_type: "m4.xlarge"                                 # General Purpose: 4 vCPU, 16 GB Memory
master_volume_size: 100                                     # 100 GB

# Slave customization
slave_vm_type: "t2.micro"                                   # General Purpose: 1 vCPU, 1 GB Memory
#slave_vm_type: "m4.4xlarge"                                 # General Purpose: 16 vCPU, 64 GB Memory
slave_volume_size: 400                                      # 400 GB

# Common properties
aws_zone: "us-east-1"                                       # North Virginia
ami_image: "ami-2051294a"                                   # RHEL-7.2_HVM_GA-20151112-x86_64-1-Hourly2-GP2
#ami_image: "ami-00a11e68"                                   # RHEL-6.5_GA_HVM-20140929-x86_64-11-Hourly2-GP2
security_groups: ['default', 'Cloudera-Tuce-New-SG']
network_id: "vpc-5a49ca3e"
subnet_id: "subnet-a0d6d48b"
ssh_user: "ec2-user"
key_pair_name: "tuce-test"